### PR TITLE
Wayfinding optimization

### LINKED ISSUE #1078: Task 2: Wayfinding
### Assignee

_No response_

### Deadline

_No response_

### What needs to change?

From the VRX manual:

> **Capability:**
System should be capable of command and control of USV to achieve a series of given goal states, specified as a series of locations/heading values.
**Implementation:**
Teams receive a list of goal states which they are free to visit in any order. The simulation continues until the maximum time is exceeded. At each time step, the combined pose error is calculated between the USV and every waypoint using the same formula for pose error distance described in the station keeping task. The performance for each waypoint is quantified by the minimum pose error achieved for that waypoint over all time steps.

Basically, ensure that the boat is able to move to a series of waypoints in order with minimal loss in accuracy.

### How would this task be tested?

1. Run the VRX simulation environment and ensure that loss is minimal by observing the topics outlined in the VRX manual.
2.
3.

### Contacts

- [ ] We need help from the mechanical team.
- [ ] We need help from the electrical team.
- [ ] We need help from Dr. Schwartz or other faculty.
- [ ] We need help from a company or an organization.
- [ ] We need help from another UF staff member or organization (ex, facilities).

### PR DESCRIPTION
**Pull request by DaniParr**
## Description

I optimized the wayfinding task accuracy by 50%. I did not change the logic of the code drastically, I simply split the steps taken by the Navigator to get to the waypoint. The 0.85 - 0.15 split means that 85% of the lengths in the x and y directions covered, the Navigator comes to a stop, and then I tell it to finish the final 15% of the path, giving it a chance to readjust

## Screenshot or Video

proof

## Related Issues

Closes #1078
\- Closes #XXX

## Testing

Open two terminal windows ->
window 1: roslaunch navigator_launch vrx.launch run_task:=False world:=wayfinding_task --screen                                                                                       
window 2: mission run Vrx

## About This PR

The documentation is up to date.
- [ X] I have updated documentation related to this change so that future members are aware of the changes I've made.

### CODE REVIEW

**Review by cbrxyz — CHANGES_REQUESTED** [review]
Thanks, great job! I tested it and it works great. Please just remember to remove your comments, and run your code through `pre-commit` to ensure it has a consistent style: https://uf-mil.github.io/docs/software/devtools.html#pre-commit

**Comment by cbrxyz** [comment]
Once this is merged in, we can close Task 2 for VRX.

**Review by cbrxyz — APPROVED** [review]
Thanks!

**Review by kawaiiPlat — APPROVED** [review]
lgtm

**Pull request merged**
