### PR TITLE
Closes Issues #205 #206

### PR DESCRIPTION
**Pull request by MarshallRawson**
Sorry Josh, I Langforded ya

### CODE REVIEW

**Comment by kev-the-dev** [comment]
Also pinging @JoshuaSiyRobotics so he is aware of the [Langforiding](https://mil.readthedocs.io/en/latest/docs/glossary.html#term-langford)

**Comment by MarshallRawson** [comment]
> Don't want to rain on any parades, but before adding 500 lines of code and a package to maintain have we considered if this functionality is provided by the existing ROS tools?
> 
> For the path_player, this seems to just be `rosbag play`
> 
> For the path_recorder, you can throttle a topic using [topic_tools/throttle](http://wiki.ros.org/topic_tools/throttle) to the desired capture frequency then use `rosbag record`

Yes currently these utilities have the same functionality as the default rosbag play / record and their default behaviors are deisnged to replicate it. However, they will give us greater flexibility in the future depending what out controller needs are. ie: what if in the future we only want to record an odom point once the robot has moved some amount of distance. This is easily implementable with these added utilities and it is not with the standard rosbag cli.

**Comment by kev-the-dev** [comment]
Ok, that makes sense

**Comment by popeyedpanther** [comment]
How is a program such as pure_pursuit suppose to retrieve all the points that represent the path? This looks like it will replay the odometry data in time.

[nav_msgs::Path](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Path.html) would allow the transfer of the entire saved path in a single latched message. We would lose velocity data but we can preserve position and orientation.

Or we could try to use [trajectory_msgs](http://docs.ros.org/api/trajectory_msgs/html/msg/JointTrajectory.html) to incorporate positions in time which speed can be inferred from. There would be some problems with the wrap around of the track and revisiting past trajectory points.

**Comment by MarshallRawson** [comment]
> How is a program such as pure_pursuit suppose to retrieve all the points that represent the path? This looks like it will replay the odometry data in time.
> 
> [nav_msgs::Path](http://docs.ros.org/melodic/api/nav_msgs/html/msg/Path.html) would allow the transfer of the entire saved path in a single latched message. We would lose velocity data but we can preserve position and orientation.
> 
> Or we could try to use [trajectory_msgs](http://docs.ros.org/api/trajectory_msgs/html/msg/JointTrajectory.html) to incorporate positions in time which speed can be inferred from. There would be some problems with the wrap around of the track and revisiting past trajectory points.

So pure_pursuit would not have the entire path at any given time, nor should it be deisnged in that way for n reasons. 

* Dealing with a large amount of data like that is going to be slow and

**Pull request merged**
