### PR TITLE
1299 alexj boat drone comms

### PR DESCRIPTION
**Pull request by alexoj46**
## Description

This PR creates a ROSSerialDevice called DroneCommDevice which allows Navigator to communicate with the drone. Also, it adds a test-suite for simulated packets.

## Screenshot or Video

Screenshot 2024-10-30 at 7 25 36 PM
Screenshot 2024-10-30 at 11 57 08 PM

## Related Issues

\- #1299 

## Testing

rosrun navigator_drone_comm test_simulated_drone.py
- This starts the test program.
- You should see a received GPSDronePacket and TargetPacket printed to the console immediately.

While "Testing receiving heartbeats for 5 secs..."
- You should see no outputted errors for missing heartbeat.

While the long test loop runs
- You should see error for no received heartbeat every second.
- Use ctrl Z to end execution.

To test services that send messages:
- Comment out lines in driver.py with “send_packet()”.
- Uncomment the print statements next to those lines.
- Now instead of freezing after sending packets, you will see print statements when messages would be sent to the drone.

Now, while the long test runs:
- Call the services below in a separate terminal to check that a message would be sent.
- Use ctrl c to end execution early.

rosservice call /test_simulated_drone/start “sample_mission”
rosservice call /test_simulated_drone/estop
rosservice call /test_simulated_drone/stop

## About This PR

- [X] I have updated documentation related to this change so that future members are aware of the changes I've made.

### CODE REVIEW

**Comment by cbrxyz** [comment]
@alexoj46 Do you remember if you were able to upload all the changes for this off from the boat/your computer? The last commit was at 11:04AM on the day the drone took a swim... :(

I'm happy to take a look whenever, but if there's still stuff to pull off the boat, I'll hold off until after break!

**Comment by alexoj46** [comment]
@cbrxyz This seems to be the most up to date version of what ended up working on the boat. I can't quite remember if there were any bugs that needed fixing after handling merge conflicts on the boat, but I believe it was relatively straightforward.

**Comment by cbrxyz** [comment]
awesome thank u for the update alex, i'll make sure to review this soon then! <3

**Comment by cbrxyz** [comment]
Looks good! I'm going to go through and make some small changes and then approve!

**Review by cbrxyz — DISMISSED** [review]
thank you alex! amazing job!!

**Pull request merged**
