### PR TITLE
Added pinger vector topic

### PR DESCRIPTION
**Pull request by alexperez33**
To test, just run the vrx simulation and see that there is a new topic called ```/wamv/sensors/pingers/pinger/boat_to_beacon_vector```. You can subscribe to it for the location of of the acoustic beacon relative to the boat/passive sonar.

### CODE REVIEW

**Comment by cbrxyz** [comment]
Do you still want to keep the topic publishing bearing alongside this new topic? If they're publishing the same information in different formats, is there any point in keeping the old topic?

**Comment by uf-mil-investigator** [comment]
Hello, it's your friendly InvestiGator bot here!

The **docs preview** for this PR is available at https://uf-mil.github.io/pr-docs/827.

```css
Last updated at:
► 321b0b0ac9be6514fccca48dc06b791f024b7b4a
► 2022-08-17 20:37 EDT
```

Have a great day! Go gators! 🐊

**Review by andrew-aj — CHANGES_REQUESTED** [review]
Investigate if passive sonar outputs normal direction vector (i.e. where positive x is the direction the boat is facing) or does what this current code emulates by subtracting the pinger position from the boat.

**Review by kawaiiPlat — APPROVED** [review]
ye

**Pull request merged**
